/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_ablearthy_tdjson_TDJson */

#ifndef _Included_io_github_ablearthy_tdjson_TDJson
#define _Included_io_github_ablearthy_tdjson_TDJson
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      io_github_ablearthy_tdjson_TDJson
 * Method:     td_1create_1client_1id
 * Signature:  ()I
 */
JNIEXPORT jint JNICALL Java_io_github_ablearthy_tdjson_TDJson_td_1create_1client_1id
  (JNIEnv *, jobject);

/*
 * Class:      io_github_ablearthy_tdjson_TDJson
 * Method:     td_1receive
 * Signature:  (D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_ablearthy_tdjson_TDJson_td_1receive
  (JNIEnv *, jobject, jdouble);

/*
 * Class:      io_github_ablearthy_tdjson_TDJson
 * Method:     td_1send
 * Signature:  (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_ablearthy_tdjson_TDJson_td_1send
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:      io_github_ablearthy_tdjson_TDJson
 * Method:     td_1execute
 * Signature:  (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_ablearthy_tdjson_TDJson_td_1execute
  (JNIEnv *, jobject, jstring);

/*
 * Class:      io_github_ablearthy_tdjson_TDJson
 * Method:     td_1set_1log_1message_1callback
 * Signature:  (ILio/github/ablearthy/tdjson/LogMessageHandler;)V
 */
JNIEXPORT void JNICALL Java_io_github_ablearthy_tdjson_TDJson_td_1set_1log_1message_1callback
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
